export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const VIEW_PRODUCT_DETAILS = 'VIEW_PRODUCT_DETAILS'
export const INCREASE_PAGE = 'INCREASE_PAGE'
export const DECREASE_PAGE = 'DECREASE_PAGE'
export const CHANGE_PAGE = 'CHANGE_PAGE'

